### PR TITLE
Added code for displaying project location and for automatic update when saving (related to #80)

### LINKED ISSUE #80: [Feature request] Show current filename
I was trying to work with multiple files earlier, and I noticed there isn't name of the current file displayed anywhere (at least not in any of the obvious places I could think of). Would it be possible to add this feature?

Personally I think the top of the OpenPonk window (marked in blue) would be great place, because it is for the most part empty, and the top of the Pharo window (marked in red) already shows the name of the current image.

image

### PR DESCRIPTION
**Pull request by sdasda7777**
(I don't know why there's so many changes, I only modified two or so lines, and the other files seem unchanged anyways)

Fixes #80  🤦‍♂️🤦‍♂️🤦‍♂️

### CODE REVIEW

**Comment by sdasda7777** [comment]
New project still looks like this:

image

But after saving, or when opening previously saved file, the path is shown as well:

image

**Comment by JanBliznicenko** [comment]
Thank you. The diffs for entire files seem like differences in line endings (or they usually are). I believe most files originally had CRLFs, but I wonder why only these were changed, to what line endings and why those with real changes are unaffected.

**Comment by sdasda7777** [comment]
I see, definitely could be the case. Should I rebase it and leave out the "unmodified" files, then?

**Comment by JanBliznicenko** [comment]
Yes, please do. Before you do, try to find what were the original and new line endings, please, so we can find out what can we do about that in the future (I fight with line endings sometimes as well).

**Comment by sdasda7777** [comment]
As far as I can tell, it seems the files I modified already had Windows newlines, whereas the other ones had Unix newlines originally 🤔
Either way it's disappointing to see that Iceberg commited something that wasn't shown on the commit review screen at all 😢

**Comment by sdasda7777** [comment]
> Either way it's disappointing to see that Iceberg commited something that wasn't shown on the commit review screen at all 😢

Although, could it be possible one of the git hooks did it? I think not, since it would most likely require the Iceberg to commit changes to those files in the first place, but I'm not completely sure.

On topic of git, I think git has some setting for forcing a newline kind for a filetype: that might be a good idea to use.

**Comment by sdasda7777** [comment]
(It seems you have to link issue from the PR, not the other way around: #80 )

Fixes #80 🤦‍♂️

**Pull request merged**
